version: '3'
services:
  ai_backend:
    build: ./ai_backend
    ports:
      - "5000:5000"
    networks:
      - backend

  ui_backend:
    build: ./ui_backend
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
